/*
 * File: dilogs_ui.h
 * Contains: Declarations of module objects, user create procedures,
 *           and callbacks.
 *
 * This file was generated by dtcodegen, from module dilogs
 *
 *    ** DO NOT MODIFY BY HAND - ALL MODIFICATIONS WILL BE LOST **
 */
#ifndef _DILOGS_UI_H_
#define _DILOGS_UI_H_

#include <stdlib.h>
#include <X11/Intrinsic.h>
#include "dtb_utils.h"

/*
 * User Interface Objects
 */
/*
 * Shared data structures
 */



/*
 * Structure Clear Procedures: These set the fields to NULL
 */

/*
 * Structure Initialization Procedures: These create the widgets
 */

/*
 * User Callbacks
 */

/*
 * Connections
 */
#endif /* _DILOGS_UI_H_ */
