/*
 * File: dilogs_ui.c
 * Contains: user module object initialize and create functions
 *
 * This file was generated by dtcodegen, from module dilogs
 *
 *    ** DO NOT MODIFY BY HAND - ALL MODIFICATIONS WILL BE LOST **
 */


#include <stdlib.h>
#include <X11/Intrinsic.h>
#include "dtb_utils.h"
#include "ui.h"
#include "dilogs_ui.h"


/*
 * Widget create procedure decls
 */

