/*** DTB_USER_CODE_START vvv Add file header below vvv ***/
/*** DTB_USER_CODE_END   ^^^ Add file header above ^^^ ***/

/*
 * File: main_win_stubs.c
 * Contains: Module callbacks and connection functions
 *
 * This file was generated by dtcodegen, from module main_win
 *
 * Any text may be added between the DTB_USER_CODE_START and
 * DTB_USER_CODE_END comments (even non-C code). Descriptive comments
 * are provided only as an aid.
 *
 *  ** EDIT ONLY WITHIN SECTIONS MARKED WITH DTB_USER_CODE COMMENTS.  **
 *  ** ALL OTHER MODIFICATIONS WILL BE OVERWRITTEN. DO NOT MODIFY OR  **
 *  ** DELETE THE GENERATED COMMENTS!                                 **
 */

#include <stdint.h>
#include <stdio.h>
#include <Xm/Xm.h>
#include "dtb_utils.h"
#include "main_win_ui.h"

/*
 * Header files for cross-module connections
 */
#include "main_win_ui.h"


/**************************************************************************
 *** DTB_USER_CODE_START
 ***
 *** All necessary header files have been included.
 ***
 *** Add include files, types, macros, externs, and user functions here.
 ***/

/*** DTB_USER_CODE_END
 ***
 *** End of user code section
 ***
 **************************************************************************/



void 
main_win_File_menu_Open_item_CB1(
    Widget widget,
    XtPointer clientData,
    XtPointer callData
)
{
    /*** DTB_USER_CODE_START vvv Add C variables and code below vvv ***/
    /*** DTB_USER_CODE_END   ^^^ Add C variables and code above ^^^ ***/
    
    DtbMainWinFileSelnInfo	dtbTarget = (DtbMainWinFileSelnInfo)clientData;
    DtbMainWinFileSelnInfo	instance = dtbTarget;	/* obsolete */
    
    if (!(dtbTarget->initialized))
    {
        dtb_main_win_file_seln_initialize(dtbTarget, dtb_main_win_mainwindow.mainwindow);
    }
    XtManageChild(instance->file_seln);
    
    /*** DTB_USER_CODE_START vvv Add C code below vvv ***/
    printf("action: main_win_File_menu_Open_item_CB1()\n");
    /*** DTB_USER_CODE_END   ^^^ Add C code above ^^^ ***/
}


void 
main_win_file_seln_CB1(
    Widget widget,
    XtPointer clientData,
    XtPointer callData
)
{
    /*** DTB_USER_CODE_START vvv Add C variables and code below vvv ***/
    /*** DTB_USER_CODE_END   ^^^ Add C variables and code above ^^^ ***/
    
    DtbMainWinFileSelnInfo	dtbTarget = (DtbMainWinFileSelnInfo)clientData;
    DtbMainWinFileSelnInfo	instance = dtbTarget;	/* obsolete */
    
    if (!(dtbTarget->initialized))
    {
        dtb_main_win_file_seln_initialize(dtbTarget, dtb_main_win_mainwindow.mainwindow);
    }
    XtUnmanageChild(instance->file_seln);
    
    /*** DTB_USER_CODE_START vvv Add C code below vvv ***/
    printf("action: main_win_file_seln_CB1()\n");
    /*** DTB_USER_CODE_END   ^^^ Add C code above ^^^ ***/
}


void 
main_win_file_seln_CB2(
    Widget widget,
    XtPointer clientData,
    XtPointer callData
)
{
    /*** DTB_USER_CODE_START vvv Add C variables and code below vvv ***/
    /*** DTB_USER_CODE_END   ^^^ Add C variables and code above ^^^ ***/
    
    DtbMainWinFileSelnInfo	dtbTarget = (DtbMainWinFileSelnInfo)clientData;
    DtbMainWinFileSelnInfo	instance = dtbTarget;	/* obsolete */
    
    if (!(dtbTarget->initialized))
    {
        dtb_main_win_file_seln_initialize(dtbTarget, dtb_main_win_mainwindow.mainwindow);
    }
    XtUnmanageChild(instance->file_seln);
    
    /*** DTB_USER_CODE_START vvv Add C code below vvv ***/
    printf("action: main_win_file_seln_CB2()\n");
    /*** DTB_USER_CODE_END   ^^^ Add C code above ^^^ ***/
}


void 
main_win_Help_menu_About_item_CB1(
    Widget widget,
    XtPointer clientData,
    XtPointer callData
)
{
    /*** DTB_USER_CODE_START vvv Add C variables and code below vvv ***/
    /*** DTB_USER_CODE_END   ^^^ Add C variables and code above ^^^ ***/
    
    DtbMainWinDialogAboutInfo	dtbTarget = (DtbMainWinDialogAboutInfo)clientData;
    DtbMainWinDialogAboutInfo	instance = dtbTarget;	/* obsolete */
    
    if (!(dtbTarget->initialized))
    {
        dtb_main_win_dialog_about_initialize(dtbTarget, dtb_main_win_mainwindow.mainwindow);
    }
    XtManageChild(instance->dialog_about_shellform);
    
    /*** DTB_USER_CODE_START vvv Add C code below vvv ***/
    printf("action: main_win_Help_menu_About_item_CB1()\n");
    /*** DTB_USER_CODE_END   ^^^ Add C code above ^^^ ***/
}


void 
main_win_about_dialog_button1_CB1(
    Widget widget,
    XtPointer clientData,
    XtPointer callData
)
{
    /*** DTB_USER_CODE_START vvv Add C variables and code below vvv ***/
    /*** DTB_USER_CODE_END   ^^^ Add C variables and code above ^^^ ***/
    
    DtbMainWinDialogAboutInfo	dtbTarget = (DtbMainWinDialogAboutInfo)clientData;
    DtbMainWinDialogAboutInfo	instance = dtbTarget;	/* obsolete */
    
    if (!(dtbTarget->initialized))
    {
        dtb_main_win_dialog_about_initialize(dtbTarget, dtb_main_win_mainwindow.mainwindow);
    }
    XtUnmanageChild(instance->dialog_about_shellform);
    
    /*** DTB_USER_CODE_START vvv Add C code below vvv ***/
    printf("action: main_win_about_dialog_button1_CB1()\n");
    /*** DTB_USER_CODE_END   ^^^ Add C code above ^^^ ***/
}


void 
main_win_Bookmarks_menu_Edit_bookmarks_item_CB1(
    Widget widget,
    XtPointer clientData,
    XtPointer callData
)
{
    /*** DTB_USER_CODE_START vvv Add C variables and code below vvv ***/
    /*** DTB_USER_CODE_END   ^^^ Add C variables and code above ^^^ ***/
    
    DtbMainWinDialogBookmarksInfo	dtbTarget = (DtbMainWinDialogBookmarksInfo)clientData;
    DtbMainWinDialogBookmarksInfo	instance = dtbTarget;	/* obsolete */
    
    if (!(dtbTarget->initialized))
    {
        dtb_main_win_dialog_bookmarks_initialize(dtbTarget, dtb_main_win_mainwindow.mainwindow);
    }
    XtManageChild(instance->dialog_bookmarks_shellform);
    
    /*** DTB_USER_CODE_START vvv Add C code below vvv ***/
    printf("action: main_win_Bookmarks_menu_Edit_bookmarks_item_CB1()\n");
    /*** DTB_USER_CODE_END   ^^^ Add C code above ^^^ ***/
}


void 
main_win_dialog_bookmarks_exit_CB1(
    Widget widget,
    XtPointer clientData,
    XtPointer callData
)
{
    /*** DTB_USER_CODE_START vvv Add C variables and code below vvv ***/
    /*** DTB_USER_CODE_END   ^^^ Add C variables and code above ^^^ ***/
    
    DtbMainWinDialogBookmarksInfo	dtbTarget = (DtbMainWinDialogBookmarksInfo)clientData;
    DtbMainWinDialogBookmarksInfo	instance = dtbTarget;	/* obsolete */
    
    if (!(dtbTarget->initialized))
    {
        dtb_main_win_dialog_bookmarks_initialize(dtbTarget, dtb_main_win_mainwindow.mainwindow);
    }
    XtUnmanageChild(instance->dialog_bookmarks_shellform);
    
    /*** DTB_USER_CODE_START vvv Add C code below vvv ***/
    printf("action: main_win_dialog_bookmarks_exit_CB1()\n");
    /*** DTB_USER_CODE_END   ^^^ Add C code above ^^^ ***/
}


void 
main_win_File_menu_Save_as_item_CB1(
    Widget widget,
    XtPointer clientData,
    XtPointer callData
)
{
    /*** DTB_USER_CODE_START vvv Add C variables and code below vvv ***/
    /*** DTB_USER_CODE_END   ^^^ Add C variables and code above ^^^ ***/
    
    DtbMainWinFileSelnSaveasInfo	dtbTarget = (DtbMainWinFileSelnSaveasInfo)clientData;
    DtbMainWinFileSelnSaveasInfo	instance = dtbTarget;	/* obsolete */
    
    if (!(dtbTarget->initialized))
    {
        dtb_main_win_file_seln_saveas_initialize(dtbTarget, dtb_main_win_mainwindow.mainwindow);
    }
    XtManageChild(instance->file_seln_saveas);
    
    /*** DTB_USER_CODE_START vvv Add C code below vvv ***/
    printf("action: main_win_File_menu_Save_as_item_CB1()\n");
    /*** DTB_USER_CODE_END   ^^^ Add C code above ^^^ ***/
}



/**************************************************************************
 *** DTB_USER_CODE_START
 ***
 *** All automatically-generated data and functions have been defined.
 ***
 *** Add new functions here, or at the top of the file.
 ***/

/*** DTB_USER_CODE_END
 ***
 *** End of user code section
 ***
 **************************************************************************/


