/*
 * File: main_win_ui.h
 * Contains: Declarations of module objects, user create procedures,
 *           and callbacks.
 *
 * This file was generated by dtcodegen, from module main_win
 *
 *    ** DO NOT MODIFY BY HAND - ALL MODIFICATIONS WILL BE LOST **
 */
#ifndef _MAIN_WIN_UI_H_
#define _MAIN_WIN_UI_H_

#include <stdlib.h>
#include <X11/Intrinsic.h>
#include "dtb_utils.h"

/*
 * User Interface Objects
 */
/*
 * Shared data structures
 */
typedef struct {
    Widget	New_window_item;
    Widget	Open_item;
    Widget	Save_as_item;
    Widget	Print_item;
    Widget	separator1_item;
    Widget	Exit_item;
} MainWinFileMenuItemsRec, *MainWinFileMenuItems;
typedef struct {
    Widget	Cut_item;
    Widget	Copy_item;
    Widget	Paste_item;
    Widget	separator2_item;
    Widget	Select_all_item;
    Widget	separator3_item;
    Widget	Refresh_Reload_item;
    Widget	Halt_loading_item;
} MainWinEditMenuItemsRec, *MainWinEditMenuItems;
typedef struct {
    Widget	Enlarge_font_item;
    Widget	Shrink_font_item;
    Widget	Default_font_size_item;
    Widget	separator1_item;
    Widget	View_page_source_item;
} MainWinViewMenuItemsRec, *MainWinViewMenuItems;
typedef struct {
    Widget	Go_to_item;
    Widget	separator1_item;
    Widget	Back_item;
    Widget	Fowards_item;
} MainWinNavigateMenuItemsRec, *MainWinNavigateMenuItems;
typedef struct {
    Widget	Add_bookmark_item;
    Widget	Edit_bookmarks_item;
    Widget	Bookmarks_item;
} MainWinBookmarksMenuItemsRec, *MainWinBookmarksMenuItems;
typedef struct {
    Widget	Security_check_item;
    Widget	Enable_live_loading_mode_item;
} MainWinOptionsMenuItemsRec, *MainWinOptionsMenuItems;
typedef struct {
    Widget	Help_page_item;
    Widget	About_item;
} MainWinHelpMenuItemsRec, *MainWinHelpMenuItems;
typedef struct {
    Widget	Bookmarks_menu2_Item1_item;
    Widget	Bookmarks_menu2_Item2_item;
} MainWinDummyMenuItemsRec, *MainWinDummyMenuItems;


typedef struct {
    Widget	File_item;
    Widget	Edit_item;
    Widget	View_item;
    Widget	Navigate_item;
    Widget	Bookmarks_item;
    Widget	Options_item;
    Widget	Help_item;
} MainWinMenubarItemsRec, *MainWinMenubarItems;
typedef struct
{
    Boolean	initialized;
    
    Widget	mainwindow;	/* object "mainwindow" */
    Widget	mainwindow_mainwin;
    Widget	mainwindow_form;
    
    Widget	menubar;	/* object "menubar" */
    MainWinMenubarItemsRec	menubar_items;
    
    Widget	mainwindow_toolbar_frame;	/* object "mainwindow_toolbar" */
    Widget	mainwindow_toolbar;
    
    Widget	mainwindow_footer;
    
    Widget	menubar_File_item_File_menu;	/* object "File_menu" */
    MainWinFileMenuItemsRec	menubar_File_item_File_menu_items;
    
    Widget	menubar_Edit_item_Edit_menu;	/* object "Edit_menu" */
    MainWinEditMenuItemsRec	menubar_Edit_item_Edit_menu_items;
    
    Widget	menubar_View_item_View_menu;	/* object "View_menu" */
    MainWinViewMenuItemsRec	menubar_View_item_View_menu_items;
    
    Widget	menubar_Navigate_item_Navigate_menu;	/* object "Navigate_menu" */
    MainWinNavigateMenuItemsRec	menubar_Navigate_item_Navigate_menu_items;
    
    Widget	menubar_Bookmarks_item_Bookmarks_menu;	/* object "Bookmarks_menu" */
    MainWinBookmarksMenuItemsRec	menubar_Bookmarks_item_Bookmarks_menu_items;
    
    Widget	Bookmarks_menu_Bookmarks_item_dummy_menu2;	/* object "dummy_menu" */
    MainWinDummyMenuItemsRec	bookmarks_menu_Bookmarks_item_dummy_menu2_items;
    
    Widget	menubar_Options_item_Options_menu;	/* object "Options_menu" */
    MainWinOptionsMenuItemsRec	menubar_Options_item_Options_menu_items;
    
    Widget	menubar_Help_item_Help_menu;	/* object "Help_menu" */
    MainWinHelpMenuItemsRec	menubar_Help_item_Help_menu_items;
    
    Widget	button_back;
    Widget	button_fowards;
    Widget	location_url;
    Widget	button_home;
    Widget	button_refresh;
    Widget	button_halt;
    Widget	button_go;
    
    Widget	drawpane_scrolledwin;	/* object "drawpane" */
    Widget	drawpane;
    
    Widget	mainwindow_label;
    
    Widget	gauge_load_rowcolumn;	/* object "gauge_load" */
    Widget	gauge_load_label;
    Widget	gauge_load;
} DtbMainWinMainwindowInfoRec, *DtbMainWinMainwindowInfo;

typedef struct
{
    Boolean	initialized;
    
    Widget	dialog_about;	/* object "dialog_about" */
    Widget	dialog_about_shellform;
    Widget	dialog_about_panedwin;
    Widget	dialog_about_form;
    
    Widget	dialog_button_panel;
    Widget	controlpane;
    Widget	label;
    Widget	about_dialog_button1;
} DtbMainWinDialogAboutInfoRec, *DtbMainWinDialogAboutInfo;

typedef struct
{
    Boolean	initialized;
    
    Widget	dialog_bookmarks;	/* object "dialog_bookmarks" */
    Widget	dialog_bookmarks_shellform;
    Widget	dialog_bookmarks_panedwin;
    Widget	dialog_bookmarks_form;
    
    Widget	dialog_button_panel2;
    Widget	controlpane2;
    
    Widget	list_scrolledwin;	/* object "list" */
    Widget	list;
    
    Widget	textfield_bookmark_name_rowcolumn;	/* object "textfield_bookmark_name" */
    Widget	textfield_bookmark_name_label;
    Widget	textfield_bookmark_name;
    
    Widget	textfield_bookmark_url_rowcolumn;	/* object "textfield_bookmark_url" */
    Widget	textfield_bookmark_url_label;
    Widget	textfield_bookmark_url;
    
    Widget	button;
    Widget	button2;
    Widget	dialog_bookmarks_save;
    Widget	dialog_bookmarks_exit;
    Widget	button_bookmarks_snarf;
} DtbMainWinDialogBookmarksInfoRec, *DtbMainWinDialogBookmarksInfo;

typedef struct
{
    Boolean	initialized;
    
    Widget	dialog_security;	/* object "dialog_security" */
    Widget	dialog_security_shellform;
    Widget	dialog_security_panedwin;
    Widget	dialog_security_form;
    
    Widget	dialog_button_panel3;
    Widget	controlpane3;
    
    Widget	textfield_url_rowcolumn;	/* object "textfield_url" */
    Widget	textfield_url_label;
    Widget	textfield_url;
    
    Widget	textfield_owner_rowcolumn;	/* object "textfield_owner" */
    Widget	textfield_owner_label;
    Widget	textfield_owner;
    
    Widget	textfield_verifier_rowcolumn;	/* object "textfield_verifier" */
    Widget	textfield_verifier_label;
    Widget	textfield_verifier;
    
    Widget	dialog_button1;
    Widget	dialog_button2;
    Widget	dialog_button3;
} DtbMainWinDialogSecurityInfoRec, *DtbMainWinDialogSecurityInfo;

typedef struct
{
    Boolean	initialized;
    
    Widget	file_seln_shell;	/* object "file_seln" */
    Widget	file_seln;
} DtbMainWinFileSelnInfoRec, *DtbMainWinFileSelnInfo;

typedef struct
{
    Boolean	initialized;
    
    Widget	file_seln_saveas_shell;	/* object "file_seln_saveas" */
    Widget	file_seln_saveas;
} DtbMainWinFileSelnSaveasInfoRec, *DtbMainWinFileSelnSaveasInfo;


extern DtbMainWinMainwindowInfoRec dtb_main_win_mainwindow;
extern DtbMainWinDialogAboutInfoRec dtb_main_win_dialog_about;
extern DtbMainWinDialogBookmarksInfoRec dtb_main_win_dialog_bookmarks;
extern DtbMainWinDialogSecurityInfoRec dtb_main_win_dialog_security;
extern DtbMainWinFileSelnInfoRec dtb_main_win_file_seln;
extern DtbMainWinFileSelnSaveasInfoRec dtb_main_win_file_seln_saveas;

/*
 * Structure Clear Procedures: These set the fields to NULL
 */
int dtbMainWinMainwindowInfo_clear(DtbMainWinMainwindowInfo instance);
int dtbMainWinDialogAboutInfo_clear(DtbMainWinDialogAboutInfo instance);
int dtbMainWinDialogBookmarksInfo_clear(DtbMainWinDialogBookmarksInfo instance);
int dtbMainWinDialogSecurityInfo_clear(DtbMainWinDialogSecurityInfo instance);
int dtbMainWinFileSelnInfo_clear(DtbMainWinFileSelnInfo instance);
int dtbMainWinFileSelnSaveasInfo_clear(DtbMainWinFileSelnSaveasInfo instance);

/*
 * Structure Initialization Procedures: These create the widgets
 */
int dtb_main_win_mainwindow_initialize(
    DtbMainWinMainwindowInfo	instance,
    Widget	parent
);
int dtb_main_win_dialog_about_initialize(
    DtbMainWinDialogAboutInfo	instance,
    Widget	parent
);
int dtb_main_win_dialog_bookmarks_initialize(
    DtbMainWinDialogBookmarksInfo	instance,
    Widget	parent
);
int dtb_main_win_dialog_security_initialize(
    DtbMainWinDialogSecurityInfo	instance,
    Widget	parent
);
int dtb_main_win_file_seln_initialize(
    DtbMainWinFileSelnInfo	instance,
    Widget	parent
);
int dtb_main_win_file_seln_saveas_initialize(
    DtbMainWinFileSelnSaveasInfo	instance,
    Widget	parent
);

/*
 * User Callbacks
 */

/*
 * Connections
 */
void main_win_File_menu_Open_item_CB1(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);
void main_win_file_seln_CB1(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);
void main_win_file_seln_CB2(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);
void main_win_Help_menu_About_item_CB1(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);
void main_win_about_dialog_button1_CB1(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);
void main_win_Bookmarks_menu_Edit_bookmarks_item_CB1(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);
void main_win_dialog_bookmarks_exit_CB1(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);
void main_win_File_menu_Save_as_item_CB1(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);
#endif /* _MAIN_WIN_UI_H_ */
